(function () {
  'use strict';
  var MAX_HIST=8, history=[], loading=false, open=false;
  var KNOWLEDGE=[
    {keys:['octubre','previsional','sipa','tope','base imponible'],answer:'Para el devengado octubre 2026: base imponible mínima $ 146.759,98 y máxima $ 4.769.631,49. Los nuevos topes se aplican a los aportes y contribuciones de la liquidación de octubre.',link:'/tools/valores.html',label:'Ver valores fiscales'},
    {keys:['haber mínimo','jubilación mínima','haber máximo'],answer:'Desde octubre 2026, el haber mínimo es $ 435.748,51 y el haber máximo $ 2.932.174,85. El incremento mensual informado es 1,66%.',link:'/tools/valores.html',label:'Ver valores previsionales'},
    {keys:['autónomo','autónomos'],answer:'Los aportes de autónomos de octubre 2026 aumentan 1,66% respecto de septiembre. Podés consultar el importe por categoría en la calculadora.',link:'/tools/autonomos.html',label:'Calcular autónomos'},
    {keys:['f931','f.931','cargas sociales','contribuciones'],answer:'El simulador F.931 permite cargar empleados, aportes, contribuciones y ART. Para octubre 2026 usa por defecto el tope SIPA de $ 4.769.631,49, que también puede editarse.',link:'/tools/f931.html',label:'Abrir simulador F.931'},
    {keys:['sueldo','sueldos','neto','recibo'],answer:'Podés calcular sueldo neto, aportes del empleado y contribuciones patronales con el tope SIPA de octubre 2026.',link:'/tools/sueldos.html',label:'Abrir liquidador de sueldos'},
    {keys:['ganancias','siradig','cuarta categoría','4ta categoría'],answer:'La herramienta de Ganancias 4ª categoría permite importar SIRADIG, liquidar por mes y generar el resumen SICORE.',link:'/tools/ganancias.html',label:'Abrir Ganancias 4ª categoría'},
    {keys:['monotributo','recategorización'],answer:'La calculadora de Monotributo determina la categoría según ingresos y parámetros, y muestra la cuota mensual vigente.',link:'/tools/monotributo.html',label:'Calcular Monotributo'},
    {keys:['interés','resarcitorio','punitorio'],answer:'La calculadora de intereses ARCA determina intereses resarcitorios, punitorios o combinados por tramos de tasas.',link:'/tools/intereses.html',label:'Calcular intereses'},
    {keys:['vencimiento','vence','calendario'],answer:'Podés consultar el calendario 2026 de IVA, F.931, Monotributo, Autónomos y otros vencimientos por terminación de CUIT.',link:'/tools/vencimientos.html',label:'Ver vencimientos'},
    {keys:['fal','fondo de asistencia laboral'],answer:'El simulador FAL proyecta aportes y saldo acumulado con plazo, rendimiento y comisión editables.',link:'/tools/fal.html',label:'Abrir simulador FAL'}
  ];
  var style=document.createElement('style');
  style.textContent='#ib-btn{position:fixed;bottom:20px;left:20px;z-index:9990;background:#1e90d4;color:#fff;border:0;border-radius:50px;padding:12px 18px;font-size:15px;font-weight:700;cursor:pointer;box-shadow:0 4px 16px rgba(0,0,0,.35);display:flex;align-items:center;gap:8px;transition:transform .15s}#ib-btn:hover{transform:scale(1.05)}#ib-panel{position:fixed;bottom:78px;left:20px;width:min(360px,calc(100vw - 40px));height:min(520px,calc(100vh - 110px));background:#2d4f68;border:1px solid #4d7a96;border-radius:16px;box-shadow:0 8px 32px rgba(0,0,0,.4);z-index:9990;display:none;flex-direction:column;overflow:hidden;font-family:inherit}#ib-header{background:#1e3a4e;padding:12px 16px;display:flex;align-items:center;justify-content:space-between}#ib-header span{color:#f0f6fb;font-weight:700;font-size:14px}#ib-close{background:none;border:0;color:#9dbdd6;font-size:20px;cursor:pointer}#ib-msgs{flex:1;overflow-y:auto;padding:12px;display:flex;flex-direction:column;gap:8px}.ib-msg{max-width:88%;padding:9px 13px;border-radius:12px;font-size:13px;line-height:1.5;overflow-wrap:anywhere;white-space:pre-line}.ib-msg.bot{background:#375e7a;color:#f0f6fb;align-self:flex-start}.ib-msg.user{background:#1e90d4;color:#fff;align-self:flex-end}.ib-link{display:inline-block;margin-top:7px;color:#fff;font-weight:700;text-decoration:underline}.ib-typing{padding:10px 13px;background:#375e7a;color:#9dbdd6;border-radius:12px;align-self:flex-start}#ib-form{display:flex;gap:8px;padding:10px 12px;background:#1e3a4e;border-top:1px solid #4d7a96}#ib-input{flex:1;background:#2d4f68;border:1px solid #4d7a96;border-radius:8px;padding:8px 12px;color:#f0f6fb;font-size:13px;resize:none;height:40px;font-family:inherit}#ib-send{background:#1e90d4;border:0;border-radius:8px;color:#fff;padding:8px 14px;cursor:pointer}#ib-note{padding:7px 12px;background:#1e3a4e;color:#9dbdd6;font-size:10px;text-align:center}@media(max-width:600px){#ib-btn{left:12px;bottom:12px}#ib-panel{left:10px;bottom:68px;width:calc(100vw - 20px)}}';
  document.head.appendChild(style);
  var btn=document.createElement('button'); btn.id='ib-btn'; btn.setAttribute('aria-label','Abrir asistente ImpoBot'); btn.innerHTML='🤖 <span>Preguntale a ImpoBot</span>'; document.body.appendChild(btn);
  var panel=document.createElement('section'); panel.id='ib-panel'; panel.setAttribute('aria-label','Asistente fiscal ImpoBot'); panel.innerHTML='<div id="ib-header"><span>🤖 ImpoBot — Asistente fiscal</span><button id="ib-close" aria-label="Cerrar">✕</button></div><div id="ib-msgs" aria-live="polite"></div><div id="ib-form"><textarea id="ib-input" placeholder="Ej.: ¿Cuál es el tope SIPA de octubre?" rows="1"></textarea><button id="ib-send" aria-label="Enviar">➤</button></div><div id="ib-note">Información orientativa · verificá la normativa aplicable a tu caso</div>'; document.body.appendChild(panel);
  function normalize(text){return text.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');}
  function localAnswer(text){var q=normalize(text),best=null,bestScore=0;KNOWLEDGE.forEach(function(item){var score=item.keys.reduce(function(n,key){return n+(q.indexOf(normalize(key))>=0?1:0);},0);if(score>bestScore){best=item;bestScore=score;}});return bestScore?best:null;}
  function addMsg(role,text,link,label){var msgs=document.getElementById('ib-msgs'),div=document.createElement('div');div.className='ib-msg '+role;div.textContent=text;if(link){var a=document.createElement('a');a.className='ib-link';a.href=link;a.textContent=label||'Abrir herramienta';div.appendChild(document.createElement('br'));div.appendChild(a);}msgs.appendChild(div);msgs.scrollTop=msgs.scrollHeight;}
  async function askServer(text){var res=await fetch('/.netlify/functions/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,history:history.slice(-MAX_HIST)})});if(!res.ok)throw new Error('unavailable');return res.json();}
  async function sendMsg(){var input=document.getElementById('ib-input'),text=(input.value||'').trim();if(!text||loading)return;input.value='';addMsg('user',text);loading=true;var msgs=document.getElementById('ib-msgs'),typing=document.createElement('div');typing.className='ib-typing';typing.textContent='Escribiendo…';msgs.appendChild(typing);var known=localAnswer(text);try{if(known){typing.remove();addMsg('bot',known.answer,known.link,known.label);history.push({role:'user',content:text},{role:'assistant',content:known.answer});}else{var data=await askServer(text);typing.remove();addMsg('bot',data.answer);history.push({role:'user',content:text},{role:'assistant',content:data.answer});}}catch(e){typing.remove();addMsg('bot','Todavía no tengo una respuesta segura para esa consulta. Podés usar las herramientas del sitio o consultar al estudio por WhatsApp.','/#servicios','Ver herramientas y contacto');}history=history.slice(-MAX_HIST*2);loading=false;}
  function welcome(){if(!document.getElementById('ib-msgs').children.length)addMsg('bot','¡Hola! Soy ImpoBot. Preguntame por topes previsionales, sueldos, F.931, Autónomos, Monotributo, Ganancias, vencimientos o intereses.');}
  btn.addEventListener('click',function(){open=!open;panel.style.display=open?'flex':'none';if(open){welcome();document.getElementById('ib-input').focus();}});document.getElementById('ib-close').addEventListener('click',function(){open=false;panel.style.display='none';});document.getElementById('ib-send').addEventListener('click',sendMsg);document.getElementById('ib-input').addEventListener('keydown',function(e){if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendMsg();}});
})();
