'use strict';
(function(){
const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS'}).format(n);
const rates={mono:[['0','Sin IVA']],ri:[['0','0 %'],['10.5','10,5 %'],['21','21 %'],['27','27 %']]};
let draft=null;
function number(v){const n=Number(v);return Number.isFinite(n)?n:NaN}
function cents(n){return Math.round((n+Number.EPSILON)*100)/100}
function cuitValid(c){if(!/^\d{11}$/.test(c))return false;const w=[5,4,3,2,7,6,5,4,3,2];const r=11-(w.reduce((s,x,i)=>s+x*Number(c[i]),0)%11);return (r===11?0:r===10?9:r)===Number(c[10])}
function digits(v){return v.replace(/\D/g,'')}
function updateTypes(){const mono=$('tax-status').value==='mono';$('type').innerHTML=mono?'<option value="C">Factura C</option>':'<option value="A">Factura A</option><option value="B">Factura B</option>';document.querySelectorAll('.rate').forEach(sel=>{const old=sel.value;sel.replaceChildren(...rates[mono?'mono':'ri'].map(([value,label])=>new Option(label,value)));if(!mono&&rates.ri.some(([v])=>v===old))sel.value=old});calculate()}
function addItem(){const tr=document.createElement('tr');tr.innerHTML='<td><input class="description" maxlength="160" required aria-label="Descripción"></td><td><input class="quantity" type="number" min="0.001" step="any" value="1" required aria-label="Cantidad"></td><td><input class="price" type="number" min="0" step="0.01" value="0" required aria-label="Precio unitario"></td><td><select class="rate" aria-label="Alícuota de IVA"></select></td><td class="line-total">$ 0,00</td><td><button class="danger remove" type="button" aria-label="Quitar concepto">×</button></td>';$('items').append(tr);tr.querySelector('.remove').addEventListener('click',()=>{if($('items').children.length>1){tr.remove();calculate()}});updateTypes()}
function calculate(){let net=0,vat=0;document.querySelectorAll('#items tr').forEach(row=>{const qty=number(row.querySelector('.quantity').value),price=number(row.querySelector('.price').value),rate=number(row.querySelector('.rate').value);if(qty>0&&price>=0){const subtotal=cents(qty*price),tax=cents(subtotal*rate/100);net+=subtotal;vat+=tax;row.querySelector('.line-total').textContent=money(subtotal+tax)}else row.querySelector('.line-total').textContent='—'});$('net').textContent=money(cents(net));$('vat').textContent=money(cents(vat));$('total').textContent=money(cents(net+vat));draft=null;$('download').disabled=true;$('result').hidden=true}
function makeDraft(){const issuer=digits($('issuer').value),doc=digits($('recipient-doc').value),kind=$('doc-type').value,concept=$('concept').value,from=$('service-from').value,to=$('service-to').value;
if(!cuitValid(issuer))throw Error('Revisá el CUIT del emisor.');if(!$('issuer-name').value.trim())throw Error('Completá la razón social del emisor.');
if(kind==='80'&&!cuitValid(doc))throw Error('Revisá el CUIT del receptor.');if(kind==='96'&&!/^\d{7,8}$/.test(doc))throw Error('Ingresá un DNI válido.');if(kind==='99'&&doc)throw Error('Para consumidor final sin documento, dejá vacío el número.');if(!$('recipient-name').value.trim())throw Error('Completá el nombre del receptor.');
const pv=number($('pos').value);if(!Number.isInteger(pv)||pv<1||pv>99999)throw Error('Ingresá un punto de venta válido.');if(!$('date').value)throw Error('Ingresá la fecha del comprobante.');if(concept!=='1'&&(!from||!to||from>to))throw Error('Completá un período de servicios válido.');
const items=[...document.querySelectorAll('#items tr')].map(row=>{const description=row.querySelector('.description').value.trim(),quantity=number(row.querySelector('.quantity').value),unitPrice=number(row.querySelector('.price').value),vatRate=number(row.querySelector('.rate').value);if(!description||!Number.isFinite(quantity)||quantity<=0||!Number.isFinite(unitPrice)||unitPrice<0)throw Error('Revisá descripción, cantidad y precio de cada concepto.');const net=cents(quantity*unitPrice);return{description,quantity,unitPrice,vatRate,net,vat:cents(net*vatRate/100)}});
const net=cents(items.reduce((sum,item)=>sum+item.net,0)),vat=cents(items.reduce((sum,item)=>sum+item.vat,0));if(net+vat<=0)throw Error('El total debe ser mayor que cero.');return{status:'BORRADOR_NO_FISCAL',issuer:{cuit:issuer,name:$('issuer-name').value.trim(),taxStatus:$('tax-status').value},type:$('type').value,date:$('date').value,pointOfSale:pv,currency:'PES',concept:Number(concept),servicePeriod:concept==='1'?null:{from,to},recipient:{docType:Number(kind),docNumber:doc,name:$('recipient-name').value.trim()},items,totals:{net,vat,total:cents(net+vat)},cae:null,number:null}}
$('items-add').addEventListener('click',addItem);$('tax-status').addEventListener('change',updateTypes);$('concept').addEventListener('change',()=>{const show=$('concept').value!=='1';$('service-from-wrap').hidden=!show;$('service-to-wrap').hidden=!show;calculate()});$('doc-type').addEventListener('change',()=>{$('recipient-doc').disabled=$('doc-type').value==='99';if($('recipient-doc').disabled)$('recipient-doc').value='';calculate()});$('draft').addEventListener('input',calculate);$('items').addEventListener('change',calculate);
$('draft').addEventListener('submit',e=>{e.preventDefault();try{draft=makeDraft();$('errors').textContent='';$('result').hidden=false;$('preview').textContent=`BORRADOR · Sin CAE ni numeración fiscal\n${draft.issuer.name} (${draft.issuer.cuit})\nFactura ${draft.type} · Punto de venta ${String(draft.pointOfSale).padStart(5,'0')} · ${draft.date}\nReceptor: ${draft.recipient.name} (${draft.recipient.docNumber||'sin documento'})\n\n${draft.items.map(i=>`${i.description}: ${i.quantity} × ${money(i.unitPrice)} · IVA ${i.vatRate}% → ${money(i.net+i.vat)}`).join('\n')}\n\nNeto: ${money(draft.totals.net)} · IVA: ${money(draft.totals.vat)} · TOTAL: ${money(draft.totals.total)}`;$('download').disabled=false}catch(error){draft=null;$('download').disabled=true;$('result').hidden=true;$('errors').textContent=error.message}});
$('download').addEventListener('click',()=>{if(!draft)return;const url=URL.createObjectURL(new Blob([JSON.stringify(draft,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`borrador-${draft.issuer.cuit}-${draft.date}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
$('date').value=new Date().toLocaleDateString('en-CA',{timeZone:'America/Argentina/Buenos_Aires'});addItem();
})();
